[Colors]
accent={color5}
background={background}
background_fullscreen={background}
folderview={color0}
folderview_topbar={color0}
icons={foreground}
overlay={color0}
overlay_text={foreground}
scrollbar={color8}
text={foreground}
tid=1
widget={color0}
widget_border={color0}
