--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/srch/imgs/bg/wal/30.Rembrandt_-_Aristotle_with_a_Bust_of_Homer_-_WGA19232.jpg"

-- Special
background="#0e1521"
foreground="#c2c4c7"
cursor="#c2c4c7"

-- Colors
color0="#0e1521"
color1="#433C42"
color2="#675549"
color3="#88613C"
color4="#8D7257"
color5="#A48C6D"
color6="#C8A171"
color7="#c2c4c7"
color8="#5d6472"
color9="#433C42"
color10="#675549"
color11="#88613C"
color12="#8D7257"
color13="#A48C6D"
color14="#C8A171"
color15="#c2c4c7"
