# Shell variables
# Generated by 'wal'
wallpaper="/home/srch/imgs/bg/wal/30.Rembrandt_-_Aristotle_with_a_Bust_of_Homer_-_WGA19232.jpg"

# Special
background='#0e1521'
foreground='#c2c4c7'
cursor='#c2c4c7'

# Colors
color0='#0e1521'
color1='#433C42'
color2='#675549'
color3='#88613C'
color4='#8D7257'
color5='#A48C6D'
color6='#C8A171'
color7='#c2c4c7'
color8='#5d6472'
color9='#433C42'
color10='#675549'
color11='#88613C'
color12='#8D7257'
color13='#A48C6D'
color14='#C8A171'
color15='#c2c4c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
